package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x64/jdk8u361/3183/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, January 9, 2023 8:31:50 AM GMT
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
  	 * The value representing REQUEST_PROCESSING_POLICY_ID.
  	 */
  public static final int value = (int)(22L);
}
